version: '3'
services:
  postgres:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: lab-psql
    environment:
      - POSTGRES_USER=postgres        # Set the PostgreSQL username
      - POSTGRES_PASSWORD=postgres # Set the PostgreSQL password
      - POSTGRES_DB=lab-psql      # Set the name of the database to be created
    ports:
      - "5432:5432"   # Expose PostgreSQL port 5432 to the host
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data in a named volume
    restart: unless-stopped  # Restart policy to always keep PostgreSQL running

volumes:
  postgres-data:
    driver: local  # Use local driver for data persistence